GOOGLE_API_KEY="AIzaSyD6fv2qZAcRc30uDjn96CbsM6pUJwLkdFE"
GOOGLE_API_KEY_1="AIzaSyCekUE-sNiAc_Jw-TFaLO11Xn18lLc-Lkw"
GOOGLE_API_KEY_2="AIzaSyBwt155qACwM5TacpTkwftEGR3CyeQGhRk"
GROQ_API_KEY = "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"
MY_PROJECT_ID="focused-service-447410-q8"
PINECONE_API_KEY="pcsk_3EcDrL_3mUVa7rhMVLMFBZJFPvgGEaunymPs7T5XcZXjBp9dF55S73miNRzeW2FMsFWcEb"