GOOGLE_API_KEY="AIzaSyD6fv2qZAcRc30uDjn96CbsM6pUJwLkdFE"
GOOGLE_API_KEY_1="AIzaSyCekUE-sNiAc_Jw-TFaLO11Xn18lLc-Lkw"
PINECONE_API_KEY="pcsk_3EcDrL_3mUVa7rhMVLMFBZJFPvgGEaunymPs7T5XcZXjBp9dF55S73miNRzeW2FMsFWcEb"